import os
import argparse
import json
import numpy as np
import tensorflow as tf
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
import matplotlib.pyplot as plt
import seaborn as sns


def load_dataset(data_dir: str):
    Xi = np.load(os.path.join(data_dir, 'X_images.npy'))
    Xf = np.load(os.path.join(data_dir, 'X_features.npy'))
    y = np.load(os.path.join(data_dir, 'y_labels.npy'))
    return Xi, Xf, y


def chronological_split(Xi, Xf, y, train_ratio=0.7, val_ratio=0.15):
    n = len(y)
    n_train = int(n * train_ratio)
    n_val = int(n * val_ratio)
    return (
        (Xi[:n_train], Xf[:n_train], y[:n_train]),
        (Xi[n_train:n_train+n_val], Xf[n_train:n_train+n_val], y[n_train:n_train+n_val]),
        (Xi[n_train+n_val:], Xf[n_train+n_val:], y[n_train+n_val:])
    )


def plot_confusion_matrix(cm, out_path):
    plt.figure(figsize=(5,4))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False)
    plt.xlabel('Predicted')
    plt.ylabel('Actual')
    plt.title('Confusion Matrix')
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    plt.tight_layout()
    plt.savefig(out_path)
    plt.close()


def plot_pred_vs_actual(y_true, y_pred, out_path):
    plt.figure(figsize=(10,3))
    plt.plot(y_true, label='Actual', drawstyle='steps-post')
    plt.plot(y_pred, label='Predicted', drawstyle='steps-post', alpha=0.8)
    plt.yticks([0,1])
    plt.legend()
    plt.title('Predicted vs Actual (Test)')
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    plt.tight_layout()
    plt.savefig(out_path)
    plt.close()


def main(args):
    Xi, Xf, y = load_dataset(args.data_dir)
    (_, _, _), (_, _, _), (Xi_te, Xf_te, y_te) = chronological_split(Xi, Xf, y, train_ratio=args.train_ratio, val_ratio=args.val_ratio)

    model = tf.keras.models.load_model(args.model_path)

    probs = model.predict([Xi_te, Xf_te], batch_size=256, verbose=0)
    y_pred = np.argmax(probs, axis=1)

    acc = accuracy_score(y_te, y_pred)
    prec = precision_score(y_te, y_pred, zero_division=0)
    rec = recall_score(y_te, y_pred, zero_division=0)
    f1 = f1_score(y_te, y_pred, zero_division=0)
    cm = confusion_matrix(y_te, y_pred)

    os.makedirs(args.plots_dir, exist_ok=True)
    metrics = {
        'accuracy': float(acc),
        'precision': float(prec),
        'recall': float(rec),
        'f1': float(f1)
    }
    with open(os.path.join(args.plots_dir, 'metrics.json'), 'w') as f:
        json.dump(metrics, f, indent=2)
    with open(os.path.join(args.plots_dir, 'classification_report.txt'), 'w') as f:
        f.write(classification_report(y_te, y_pred, digits=4))

    plot_confusion_matrix(cm, os.path.join(args.plots_dir, 'confusion_matrix.png'))
    plot_pred_vs_actual(y_te, y_pred, os.path.join(args.plots_dir, 'pred_vs_actual.png'))

    # If a training curve exists, copy name is already accuracy_curve.png generated by training
    print('Evaluation done. Metrics saved to', args.plots_dir)


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--data_dir', type=str, default='IMD_Project/GASF_images')
    parser.add_argument('--model_path', type=str, default='IMD_Project/models/model_cnn.h5')
    parser.add_argument('--plots_dir', type=str, default='IMD_Project/static/plots')
    parser.add_argument('--train_ratio', type=float, default=0.7)
    parser.add_argument('--val_ratio', type=float, default=0.15)
    args = parser.parse_args()
    main(args)
